name: Build ASP.NET Core

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: List files
        run: ls ${{github.workspace}}

      - name: Print Github Context
        env:
          Github_Context: {{ toJson(github)}}
        run: echo "$Github_Context"

